#!/usr/bin/env node
import { Command } from 'commander';
import * as path from 'path';
import * as fs from 'fs';
import { TruthGatewayClient } from '../core/GatewayClient';
import { RecipeDefinition } from '../core/recipe';

const program = new Command();

program
    .name('taas')
    .description('CLI for the TaaS (The API Standard) Protocol')
    .version('1.2.0');

/**
 * Command: init
 * Scaffolds a new recipe file.
 */
program
    .command('init')
    .description('Initialize a new TaaS Recipe blueprint')
    .argument('<name>', 'Name of the recipe file (e.g. my-recipe)')
    .action((name) => {
        const fileName = name.endsWith('.ts') ? name : `${name}.ts`;
        const filePath = path.resolve(process.cwd(), fileName);

        const template = `import { Recipe, Step, Truth } from '@friehub/taas-sdk';

/**
 * ${name} - Generated by TaaS CLI
 */
export const recipe = Recipe.define({
    name: "${name}",
    description: "Autogenerated TaaS Recipe",
    category: "GENERAL",
    outcomeType: "BINARY"
})
.handler(async (inputs) => {
    // Write your truth-seeking logic here
    const data = await Truth.fetch('some.provider', { param: 'value' });
    return data;
});
`;

        fs.writeFileSync(filePath, template);
        console.log(`\x1b[32m✔\x1b[0m Recipe initialized at ${filePath}`);
    });

/**
 * Command: compile
 * Compiles a TS recipe to JSON.
 */
program
    .command('compile')
    .description('Compile a TypeScript recipe into a protocol-compliant JSON blueprint')
    .argument('<file>', 'Path to the recipe .ts file')
    .option('-o, --output <path>', 'Output JSON file path')
    .action(async (file, options) => {
        try {
            const filePath = path.resolve(process.cwd(), file);

            // Register ts-node to handle the recipe file
            require('ts-node').register({ transpileOnly: true });

            const module = require(filePath);
            const recipe: RecipeDefinition = module.recipe || module.default;

            if (!recipe || !(recipe instanceof RecipeDefinition)) {
                console.error(`\x1b[31m✘\x1b[0m Error: File must export a 'RecipeDefinition' instance as 'recipe' or default.`);
                process.exit(1);
            }

            const blueprint = await recipe.compile();
            const outputPath = options.output || file.replace('.ts', '.json');

            fs.writeFileSync(path.resolve(process.cwd(), outputPath), JSON.stringify(blueprint, null, 2));
            console.log(`\x1b[32m✔\x1b[0m Blueprint compiled successfully: ${outputPath}`);
        } catch (error: any) {
            console.error(`\x1b[31m✘\x1b[0m Compilation failed: ${error.message}`);
            process.exit(1);
        }
    });

/**
 * Command: deploy
 * Compiles and registers with the gateway.
 */
program
    .command('deploy')
    .description('Compile and register a recipe with the TaaS Gateway')
    .argument('<file>', 'Path to the recipe .ts file')
    .option('-g, --gateway <url>', 'Gateway URL', 'https://gateway.friehub.cloud')
    .option('-t, --token <token>', 'Authorization token (EIP-712 or Secret)')
    .action(async (file, options) => {
        try {
            const filePath = path.resolve(process.cwd(), file);
            require('ts-node').register({ transpileOnly: true });

            const module = require(filePath);
            const recipe: RecipeDefinition = module.recipe || module.default;

            const client = new TruthGatewayClient(options.gateway);
            const token = options.token || process.env.TAAS_AUTH_TOKEN;

            console.log(`\x1b[34mℹ\x1b[0m Deploying ${recipe.config.name} to ${options.gateway}...`);
            const result = await recipe.deploy(client, token);

            console.log(`\x1b[32m✔\x1b[0m Recipe deployed successfully!`);
            console.log(`\x1b[32m✔\x1b[0m Recipe ID: ${result.id}`);
        } catch (error: any) {
            const msg = error.response?.data?.error || error.message;
            console.error(`\x1b[31m✘\x1b[0m Deployment failed: ${msg}`);
            process.exit(1);
        }
    });

program.parse();
